# Generated by Django 4.2.1 on 2023-06-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('election_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('election_description', models.TextField()),
                ('participant_due_date', models.DateField()),
                ('election_start_date', models.DateTimeField()),
                ('election_end_date', models.DateTimeField()),
                ('election_result_date', models.DateField()),
                ('result', models.JSONField()),
                ('registration_close', models.BooleanField(default=False)),
                ('area', models.ManyToManyField(to='Election.area')),
            ],
        ),
    ]
