# Generated by Django 4.2.1 on 2023-06-13 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Login', '0001_initial'),
        ('Candidate_Login', '0003_participant_is_rejected'),
        ('Election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidate_Login.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Election.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Login.userprofile')),
            ],
        ),
    ]
