# Generated by Django 4.2.1 on 2023-06-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Login', '0001_initial'),
        ('Election', '0002_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'election')},
        ),
    ]
