# Generated by Django 4.2.1 on 2023-06-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0006_vote_election_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='election_name',
        ),
    ]
