# Generated by Django 4.2.1 on 2023-06-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate_Login', '0002_participant_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
